change package version

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -46,7 +46,16 @@ jobs:
         run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM }}" > ~/.npmrc
       - name: Extract version
         id: get_version
-        run: echo "PACKAGE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
+        run: |
+          TAG_NAME="${GITHUB_REF#refs/tags/}"
+          VERSION=$(echo "$TAG_NAME" | sed -E 's/^v([0-9]+\.[0-9]+\.[0-9]+).*/\1/')
+          if [[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "PACKAGE_VERSION=$VERSION" >> $GITHUB_ENV
+          else
+            echo "Invalid tag format. Expected 'vX.Y.Z'." >> $GITHUB_ENV
+            exit 1
+          fi
+        shell: bash
       - name: Set version and publish eslint package
         run: |
           cd packages/eslint
@@ -63,10 +72,19 @@ jobs:
       - name: Install dependencies
         run: npm ci
       - name: Configure NPM authentication
-        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.TEST }}" > ~/.npmrc
+        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM }}" > ~/.npmrc
       - name: Extract version
         id: get_version
-        run: echo "PACKAGE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
+        run: |
+          TAG_NAME="${GITHUB_REF#refs/tags/}"
+          VERSION=$(echo "$TAG_NAME" | sed -E 's/^v([0-9]+\.[0-9]+\.[0-9]+).*/\1/')
+          if [[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "PACKAGE_VERSION=$VERSION" >> $GITHUB_ENV
+          else
+            echo "Invalid tag format. Expected 'vX.Y.Z'." >> $GITHUB_ENV
+            exit 1
+          fi
+        shell: bash
       - name: Set version and publish stylelint package
         run: |
           cd packages/stylelint
@@ -86,7 +104,16 @@ jobs:
         run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM }}" > ~/.npmrc
       - name: Extract version
         id: get_version
-        run: echo "PACKAGE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
+        run: |
+          TAG_NAME="${GITHUB_REF#refs/tags/}"
+          VERSION=$(echo "$TAG_NAME" | sed -E 's/^v([0-9]+\.[0-9]+\.[0-9]+).*/\1/')
+          if [[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "PACKAGE_VERSION=$VERSION" >> $GITHUB_ENV
+          else
+            echo "Invalid tag format. Expected 'vX.Y.Z'." >> $GITHUB_ENV
+            exit 1
+          fi
+        shell: bash
       - name: Set version and publish prettier package
         run: |
           cd packages/prettier
